import { useQuery } from '@apollo/react-hooks';
import React from 'react';
import { gql } from 'apollo-boost'
import { useHelloQuery, useTestingQuery } from './generated/graphql';
import {BrowserRouter, Link, Route, Switch} from 'react-router-dom';
import { Home } from './pages/Home';
import { Register } from './pages/Register';
import { Login } from './pages/Login';
import { Bye } from './pages/Bye';
import { Header } from './pages/Header';






const Routes: React.FC = () => {
  //queries are being generated by "yarn gen in the cli"
  //they can be found as components in /src/generated
  //write .graphql in /src/graphql 
  // const {data, loading} = useHelloQuery()

  return (
    <BrowserRouter>
    <div>
      <Header />
 
    </div>
    <Switch>
      <Route exact path='/' component={Home}/>
      <Route exact path='/register' component={Register}/>
      <Route exact path='/login' component={Login} />
      //protected route
      <Route exact path='/bye' component={Bye}/>
      //protected route
    </Switch>
    </BrowserRouter>
  )

};

export default Routes;
